runtime: custom
env: flex

service: risteys-r6

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  RISTEYS_FLAVOR: "blue_r6"  # will be used to populate the database name for example
