# --- COMMON DATA FILES NEEDED FOR ALL STEPS ----------------------------------

[paths]
# Path to the Kanta preprocessed data file (Parquet)
kanta_preprocessed_file = ""



# --- PIPELINE STEPS ----------------------------------------------------------

[pipeline_steps.split_by_omopid]
run = true

# Path to the directory to use for the Kanta da files split on OMOP_ID
output_directory = ""


[pipeline_steps.compute_stats]
run = true

# Path to the minimum phenotype data file (CSV).
# Needed for the variables: sex, and date of birth.
minimum_phenotype_file = ""

# Path to a directory to write the pipeline output files.
output_directory = ""
