runtime: custom
env: flex

service: default

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 8

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  RISTEYS_FLAVOR: "blue_r7"  # will be used to populate the database name for example
