Risteys – Web portal
====================

This directory contains the code to power the online FinRegistry-FinnGen Risteys web portal. For the data pipeline, please check the link:../pipeline/README.md[pipeline] directory.

The project is based on the https://phoenixframework.org/[Phoenix web framework].
This framework is written in https://elixir-lang.org/[elixir], which is also used to do data pre-processing and import data into the database.
The front-end interactions are using https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html[Phoenix LiveView].


Setting up a development environment
------------------------------------

Requirements
~~~~~~~~~~~~

- https://elixir-lang.org/install.html[elixir]
- PostgreSQL database


Configuration
~~~~~~~~~~~~~

Some configuration files contain secret credentials, therefore are not present in this public GitHub repository. Risteys developers can get them by requesting access to the GitLab repository `risteys/risteys_secrets`.


Running
~~~~~~~
Make sure you are in the directory `risteys_elixir`, then run the command

[source,bash]
----
mix phx.server
----

You can now access Risteys at http://localhost:4000


Importing data
--------------

Once the Risteys web server is running we still need to put data there.

If you need to compute the statistics by yourself, then check the link:../pipeline/README.md[pipeline documentation].

When you have the data, you can proceed to import it into the Risteys database.
The scripts to import data files into the Risteys database are in this current directory (`risteys_elixir`) and they should be run from that directory, for example:

[source,bash]
----
mix run import_icd9.exs <path-to-input-file>
----


Import scripts should be run in this order:

1. import_icd10.exs, using:
  - <<file-medcode,FG Medcode>>

2. import_icd9.exs, using:
  - <<file-medcode,FG Medcode>>

3. import_endpoint_csv.exs, using:
  - <<file-endp-defs,FG Endpoint definitions>>
  - <<file-endp-main-tag,FG Endpoint main tag>>
  - <<file-endp-taglist,FG Endpoint tag list>>
  - <<file-icd10,ICD-10>>
  - <<file-endp-selected-core,FG Endpoint selected core>>

4. import_intermediate_counts.exs, using:
  - <<file-interm-counts,FG intermediate counts>> and `FG` as dataset argument.

5. import_ontology.exs, using:
  - <<file-ontology,Risteys ontology>>
  - <<file-corrected-descriptions,Risteys corrected endpoint descriptions>>

6. import_excluded_endpoints.exs, using:
  - <<file-excluded_endp,FinRegistry excluded endpoints>>

7. import_key_figures.exs, using:
  - <<file-key-fig-FR-all,Risteys FinRegistry key figures of full population>> and `FR` as dataset argument

8. import_key_figures.exs, using:
  - <<file-key-fig-FR-index,Risteys FinRegistry key figures of index-persons>> and `FR_index` as dataset argument

9. import_key_figures.exs, using:
  - <<file-key-fig-FG,Risteys FinnGen key figures>> and `FG` as dataset argument

10. import_distributions.exs, using:
  - <<file-distrib-age-FR,Risteys FinRegistry age distributions>> and `age` and `FR` as arguments

11. import_distributions.exs, using:
  - <<file-distrib-year-FR,Risteys FinRegistry year distributions>> and `year` and `FR` as arguments

12. import_distributions.exs, using:
  - <<file-distrib-age-FG,Risteys FinnGen age distributions>> and `age` and `FG` as arguments

13. import_distributions.exs, using:
  - <<file-distrib-year-FG,Risteys Finngen year distributions>> and `year` and `FG` as arguments

14. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FR,Risteys FinRegistry cumulative incidence>> and `FR` as argument

15. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FG,Risteys FinnGen cumulative incidence>> and `FG` as argument

16. import_interactive_mortality_baseline.exs, using:
  - <<file-mortality-baseline,Risteys FinRegistry mortality baseline cumulative hazards>>

17. import_interactive_mortality_params.exs, using:
  - <<file-mortality-params,Risteys FinRegistry mortality parameters>>

18. import_mortality_counts.exs, using:
  - <<file-mortality-counts,Risteys FinRegistry mortality counts>>

19. import_correlation.exs, using:
  - <<file-corr-pheno-geno,FinnGen phenotypic + genotypic correlations>>
  - <<file-coloc-variants,FinnGen coloc variants>>

20. import_case_overlaps_fr.exs, using:
  - <<file-case-overlaps-FR, FinRegistry case overlaps>>

21. import_coxhr.exs, using
  - <<file-surv-FR, FinRegistry survival analysis results>>

22. import_genetic_correlations.exs, using
  - <<file-gen-correlations, FinnGen LDSC genetic correlations>>

23. import_genes.exs, using
  - <<file-havana-genes, HAVANA gene list>>

24. import_upset_plots.exs, using
  - <<file-upset-plots, Upset Plots>> and `FG` as dataset argument

25. import_codewas.exs, using
  - <<file-codewas-endpoints, CodeWAS Endpoints>>
  - <<file-codewas-codelist, CodeWAS code list>>

26. `Risteys.LabWAS.import_stats`, using:
  - <<file-labwas, LabWAS data>>

27. `Risteys.OMOP.import_lab_test_omop_concepts`, using:
  - <<file-kanta-lab-omopid-list, Kanta lab – List of OMOP Concept IDs>>
  - <<file-omop-concepts, OMOP (LOINC + SNOMED) – Concepts>>
  - <<file-omop-concept-relationships, OMOP (LOINC + SNOMED) – Concept relationships>>

  Can set a longer database timeout if needed, likeso:
  ```sh
  DATABASE_QUERY_TIMEOUT=120000 iex -S mix
  ```

28. `Risteys.LabTestStats.import_dataset_metadata`, using:
  - <<file-kanta-lab-metadata, Kanta lab – Metadata>>

29. `Risteys.LabTestStats.import_stats_npeople`, using:
  - <<file-kanta-lab-npeople, Kanta lab – Stats N People by sex>>

30. `Risteys.LabTestStats.import_stats_median_n_measurements`, using:
  - <<file-kanta-lab-median-n-measurements, Kanta lab – Median N measurements>>

31. `Risteys.LabTestStats.import_stats_people_with_two_plus_records`, using:
  - <<file-kanta-lab-people-with-two-plus-records, Kanta lab – Percent people with 2+ records>>

32. `Risteys.LabTestStats.import_stats_median_years_first_to_last`, using:
  - <<file-kanta-lab-median-years-first-to-last, Kanta lab – Median years from first to last record>>

33. `Risteys.LabTestStats.import_qc_tables`, using:
  - <<file-kanta-lab-qc-tables-stats, Kanta lab – QC tables stats>>
  - <<file-kanta-lab-qc-tables-dist-values, Kanta lab – QC tables distribution values>>
  - <<file-kanta-lab-qc-tables-dist-bins-definitions, Kanta lab – QC tables distribution binning>>
  - <<file-kanta-lab-qc-tables-test-outcomes, Kanta lab – QC tables test outcomes>>

34. `Risteys.LabTestStats.import_stats_distribution_lab_values`, using:
  - <<file-kanta-lab-dist-lab-values-continuous-stats, Kanta lab – Distribution lab values / continuous / stats>>
  - <<file-kanta-lab-dist-lab-values-continuous-binning, Kanta lab – Distribution lab values / continuous / binning>>
  - <<file-kanta-lab-dist-lab-values-discrete, Kanta lab – Distribution lab values / discrete>>

35. `Risteys.LabTestStats.import_stats_distribution_year_of_birth`, using:
  - <<file-kanta-lab-dist-yob-stats, Kanta lab – Distribution year of birth / stats>>
  - <<file-kanta-lab-dist-yob-binning, Kanta lab – Distribution year of birth / binning>>

36. `Risteys.LabTestStats.import_stats_distribution_age_first_measurement`, using:
  - <<file-kanta-lab-dist-age-first, Kanta lab – Distribution age at first measurement>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

37. `Risteys.LabTestStats.import_stats_distribution_age_last_measurement`, using:
  - <<file-kanta-lab-dist-age-last, Kanta lab – Distribution age at last measurement>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

38. `Risteys.LabTestStats.import_stats_distribution_age_start_of_registry`, using:
  - <<file-kanta-lab-dist-age-registry, Kanta lab – Distribution age at registry start>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

39. `Risteys.LabTestStats.import_stats_distribution_duration_first_to_last_measurement`, using:
  - <<file-kanta-lab-dist-duration-stats, Kanta lab – Distribution duration from first to last record / stats>>
  - <<file-kanta-lab-dist-duration-binning, Kanta lab – Distribution duration from first to last record / binning>>

40. `Risteys.LabTestStats.import_stats_distribution_n_measurement_over_years`, using:
  - <<file-kanta-lab-dist-years-stats, Kanta lab – Distribution N measurements over the years / stats>>
  - <<file-kanta-lab-dist-years-binning, Kanta lab – Distribution N measurements over the years / binning>>

41. `Risteys.LabTestStats.import_stats_distribution_n_measurements_per_person`, using:
  - <<file-kanta-lab-dist-nmeas-person-stats, Kanta lab – Distribution N measurements by person / stats>>
  - <<file-kanta-lab-dist-nmeas-person-binning, Kanta lab – Distribution N measurements by person / binning>>

42. `Risteys.LabTestStats.import_stats_distribution_value_range_per_person`, using:
  - <<file-kanta-lab-dist-value-range-stats, Kanta lab – Distribution value range / stats>>
  - <<file-kanta-lab-dist-value-range-binning, Kanta lab – Distribution value range / binning>>

43. `Risteys.LabTestStats.import_reference_range_tables`, using:
  - <<file-kanta-lab-reference-range-table, Kanta lab – Reference range table>>


File list
~~~~~~~~~

* [[file-icd10]]ICD-10
** name: `ICD10_koodistopalvelu_2015-08_26_utf8__XXH64_71956a051f960e51.csv`
** source: https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=23&versionKey=58[Kela Kansallinen koodistopalvelu]

* [[file-medcode]]FinnGen medcode
** name: `finngen_R9_medcode_ref__XXH64_708053b379a04020.tsv`
** source: FinnGen - Library Green

* [[file-endp-defs]]FinnGen endpoint definitions
** name: `finngen_R13_endpoint_core_noncore_1.0.added_omit__XXH64_954431555ae7d93f.csv`
** source: Merging of `finngen_R13_endpoint_core_noncore_1.0.xlsx` and `OMIT` column from `Endpoints_Controls_FINNGEN_ENDPOINTS_DF13_Final_2025-05-23.xlsx` - FinnGen clinical team - https://github.com/FINNGEN/Df12-endpoint-and-control-definitions/[GitHub]

* [[file-endp-main-tag]]FinnGen endpoint main tag
** name: `FINNGEN_ENDPOINTS_DF13_Final_2025-05-23.names_tagged_ordered__XXH64_b063d95e8d735a13.txt`
** source: FinnGen clinical team - Sharepoint

* [[file-endp-taglist]]FinnGen endpoint tag list
** name: `TAGLIST_DF13__XXH64_0bd0742528d594b8.csv`
** source: FinnGen clinical team - https://github.com/FINNGEN/DF13-endpoint-and-control-definitions/[GitHub]

* [[file-endp-selected-core]]FinnGen endpoint selected core
** name: `finngen_correlation_clusters_DF8__XXH64_0d9f3a10306791f5.csv`
** source: FinnGen clinical team

* [[file-interm-counts]]FinnGen endpoint intermediate counts
** name: `finngen_endpoints_intermediate_counts_green_export_R13_v2__XXH64_5ae876890fda07ef.txt`
** source: FinnGen registry team

* [[file-ontology]]Risteys ontology
** name: `finngen_ontology_2022-08-22__XXH64_2a8d4690fa4ae89a.json`
** source: Risteys pipeline

* [[file-corrected-descriptions]]Risteys corrected endpoint description
** name: `corrected-endpoint-descriptions.airtable-export.2025-07-07__XXH64_c72d06fc1ba2a08a.csv`
** source: Risteys Airtable

* [[file-excluded_endp]]FinRegistry excluded endpoints
** name: `excluded_endpoints_FR_Risteys_R13__XXH64_61f31ee228e0d6f7.csv`
** source: Risteys script `exclude_endpoints_finregistry.py`

* [[file-key-fig-FR-all]]Risteys FinRegistry key figures, all individuals
** name: `key_figures_all_2022-10-10_with_EXALLC_EXMORE__XXH64_920b310de04e72e7.csv`
** source: Risteys pipeline

* [[file-key-fig-FR-index]]Risteys FinRegistry key figures, only index-persons
** name: `key_figures_index_2022-10-10_with_EXALLC_EXMORE__XXH64_c62d6a466a0512a1.csv`
** source: Risteys pipeline

* [[file-key-fig-FG]]Risteys FinnGen key figures
** name: `key_figures_all_2025-07-04__XXH64_155c4fedea86ec6d.csv`
** source: Risteys pipeline

* [[file-distrib-age-FR]]Risteys FinRegistry age distributions
** name: `distribution_age_2022-10-10_with_EXALLC_EXMORE__XXH64_edd7be5c03a84317.csv`
** source: Risteys pipeline

* [[file-distrib-year-FR]]Risteys FinRegistry year distributions
** name: `distribution_year_2022-10-10_with_EXALLC_EXMORE__XXH64_a5ea390cd797b6e3.csv`
** source: Risteys pipeline

* [[file-distrib-age-FG]]Risteys FinnGen age distributions
** name: `distribution_age_2025-07-04__XXH64_424632e6e4c1e528.csv`
** source: Risteys pipeline

* [[file-distrib-year-FG]]Risteys FinnGen year distributions
** name: `distribution_year_2025-07-04__XXH64_ac575f4b6629f1ca.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FR]]Risteys FinRegistry cumulative incidence
** name: `cumulative_incidence_2022-10-10_with_EXALLC_EXMORE__XXH64_c08ae173edf55e72.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FG]]Risteys FinnGen cumulative incidence
** name: `all_cumulative_incidence__XXH64_9b53002eb15be9a1.csv`
** source: Risteys pipeline

* [[file-mortality-baseline]]Risteys FinRegistry mortality baseline cumulative hazards
** name: `mortality_baseline_cumulative_hazard_2022-10-11_with_EXALLC_EXMORE__XXH64_0088608aa7e021bd.csv`
** source: Risteys pipeline

* [[file-mortality-params]]Risteys FinRegistry mortality parameters
** name: `mortality_params_2022-10-11_with_EXALLC_EXMORE__XXH64_8f4fdc15e1c061c1.csv`
** source: Risteys pipeline

* [[file-mortality-counts]]Risteys FinRegistry mortality counts
** name: `mortality_counts_2022-10-11_with_EXALLC_EXMORE__XXH64_f7f9581772ec80c6.csv`
** source: Risteys pipeline

* [[file-corr-pheno-geno]]FinnGen phenotypic + genotypic correlations
** name: `corr_pheno-fg-r13_geno-fg-r13_full-join__2025-07-03__XXH64_2cfec9925af5e022.csv.zst`
** source: https://github.com/FINNGEN/endpcorr[FinnGen correlation pipeline] for the phenotypic file, merged with genotypic correlation file from FinnGen analysis team

* [[file-coloc-variants]]FinnGen coloc variants
** name: `r13.autoreport.compare.pval_lt_5e_08.r2_gt_0_8.variants.keep_cs__XXH64_69b4f7cdcbd6b85b.csv`
** source: FinnGen analysis team

* [[file-case-overlaps-FR]] FinRegistry case overlaps
** name: `case_overlap_2022-12-31__XXH64_fb1ca5ba80e4a0ba.csv.zst`
** source: Risteys pipeline

* [[file-surv-FR]] FinRegistry survival analysis results
** name: `surv_priority_endpoints_2022-12-25__XXH64_b92220411f705ef2.csv`
** source: Risteys pipeline

* [[file-gen-correlations]] FinnGen LDSC genetic correlations
** name: `finngen_R13_FIN.ldsc.summary__XXH64_93d6bd2ed6fd4f39.tsv`
** source: FinnGen Green library

* [[file-havana-genes]] HAVANA gene list
** name: `havana__XXH64_085a38684d85191e.json`
** source: HAVANA through FinnGen

* [[file-upset-plots]] Upset Plots
** Not available for DF13 yet.
** source: Harri S, FinnGen Phenotype team

* [[file-codewas-endpoints]] CodeWAS Endpoints
** name: `codewas-from-xwas__XXH64_ea4f0a73fc852fdc.jsonl.zst`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team; then applied SQL query with DuckDB:
+
[source,sql]
----
copy (
    with source as (
        select * from code_endpoint_counts_DF13_v1 as counts
        left join fg_codes_info_v9 as codes
        on (
            -- Using `is not distinct from` to join on NULL also
            counts.FG_CODE1 is not distinct from codes.FG_CODE1
            and counts.FG_CODE2 is not distinct from codes.FG_CODE2
            and counts.FG_CODE3 is not distinct from codes.FG_CODE3
            and counts.vocabulary_id is not distinct from codes.vocabulary_id
        )
    ),
    source_subset as (
        select *
        from source
        where
            -- Keep only cohort with >=50 cases and controls
            (n_cases_total >= 50)
            and (n_controls_total >= 50)
            -- Keep only records with nlog10p >= MIN_NLOG10P
            and (counts_mlogp > 6.0)
    )

    select
        ENDPOINT as endpoint_name,
        n_cases_total::UINT64 as n_matched_cases,
        n_controls_total::UINT64 as n_matched_controls,
        array_agg(
            struct_pack(
                code1 := FG_CODE1,
                code2 := FG_CODE2,
                code3 := FG_CODE3,
                description := name_en,
                vocabulary := vocabulary_id,
                -- Replace Infinity with max double, because Infinity as a double/float
                -- is not JSON compliant and will fail to parse downstream.
                odds_ratio := if(
                    isinf(counts_odds_ratio),
                    1.7976931348623157e+308,
                    counts_odds_ratio
                ),
                nlog10p := counts_mlogp,
                -- Greenize the Ns
                n_matched_cases := if(n_cases_with_code < 5, NULL, n_cases_with_code::UINT64),
                n_matched_controls := if(n_controls_with_code < 5, NULL, n_controls_with_code::UINT64)
            )
        ) as codes
    from source_subset
    group by endpoint_name, n_matched_cases, n_matched_controls
)
to 'codewas-from-xwas.jsonl.zst';
----

* [[file-codewas-codelist]] CodeWAS code list
** name: `fg_codes_info_v9.codewas__XXH64_f9a33b16990a8d57.csv`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team; then applied SQL query with DuckDB:
+
[source,sql]
----
copy (select FG_CODE1, FG_CODE2, FG_CODE3, code, vocabulary_id from fg_codes_info_v9) to 'fg_codes_info_v9.codewas.csv';
----

* [[file-labwas]] LabWAS data
** name: `labwas.XXH64_45ee892713aa9568.jsonl`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team; then applied SQL query with DuckDB:
+
[source,sql]
----
copy (
    WITH omop AS
        (
            SELECT
                concept_id,
                concept_name
            FROM concept
        )
    SELECT
        ENDPOINT AS FG_Endpoint,
        CAST(labwas_endpoints_df13_v2.CONCEPT_ID as VARCHAR) AS OMOP_Concept_ID,
        omop.concept_name AS OMOP_Concept_Name,
        CAST(n_cases_total as UINT64) AS FG_Endpoint_N_Cases,
        CAST(n_controls_total as UINT64) AS FG_Endpoint_N_Controls,
        CAST(n_cases_with_test as UINT64) AS With_Measurement_N_Cases,
        CAST(n_controls_with_test as UINT64) AS With_Measurement_N_Controls,
        if(isinf(counts_odds_ratio), 1.7976931348623157e+308, counts_odds_ratio) AS With_Measurement_Odds_Ratio,
        if(isinf(counts_mlogp), 1.7976931348623157e+308, counts_mlogp) AS With_Measurement_mlogp,
        mean_n_measurements_cases AS Mean_N_Measurements_Cases,
        mean_n_measurements_controls AS Mean_N_Measurements_Controls,
        CAST(n_cases_with_test_and_value as UINT64) AS Mean_Value_N_Cases,
        CAST(n_controls_with_test_and_value as UINT64) AS Mean_Value_N_Controls,
        unit_value_cases As Mean_Value_Unit,
        mean_value_cases AS Mean_Value_Cases,
        mean_value_controls AS Mean_Value_Controls,
        if(isinf(values_mlogp), 1.7976931348623157e+308, values_mlogp) AS Mean_Value_mlogp
    FROM labwas_endpoints_df13_v2
    LEFT JOIN omop ON labwas_endpoints_df13_v2.CONCEPT_ID = omop.concept_id
    WHERE (
        ((FG_Endpoint_N_Cases = 0) OR (FG_Endpoint_N_Cases >= 5))
        AND ((FG_Endpoint_N_Controls = 0) OR (FG_Endpoint_N_Controls >= 5))
        AND ((With_Measurement_N_Cases = 0) OR (With_Measurement_N_Cases >= 5))
        AND ((With_Measurement_N_Controls = 0) OR (With_Measurement_N_Controls >= 5))
        AND ((Mean_Value_N_Cases = 0) OR (Mean_Value_N_Cases >= 5))
        AND ((Mean_Value_N_Controls = 0) OR (Mean_Value_N_Controls >= 5))
        AND (((FG_Endpoint_N_Cases - With_Measurement_N_Cases) = 0) OR ((FG_Endpoint_N_Cases - With_Measurement_N_Cases) >= 5))
        AND (((FG_Endpoint_N_Controls - With_Measurement_N_Controls) = 0) OR ((FG_Endpoint_N_Controls - With_Measurement_N_Controls) >= 5))
        AND (((With_Measurement_N_Cases - Mean_Value_N_Cases) = 0) OR ((With_Measurement_N_Cases - Mean_Value_N_Cases) >= 5))
        AND (((With_Measurement_N_Controls - Mean_Value_N_Controls) = 0) OR ((With_Measurement_N_Controls - Mean_Value_N_Controls) >= 5))
    )
)
to 'labwas-from-xwas.jsonl.zst' (format JSON, array FALSE, compression 'zstd')
----

* [[file-kanta-lab-omopid-list]] Kanta lab – List of OMOP Concept IDs
** name: `all_omop_ids.XXH64_3407a565a43950ce.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-omop-concepts]] OMOP (LOINC + SNOMED) – Concepts
** name: `CONCEPT.xsv_fmt.XXH64_3db4f0c961550c25.csv`
** source: From https://athena.ohdsi.org/vocabulary/list[OHDSI Athena], then selected CODE (CDM V5) = LOINC (Latest update: 06-Aug-2024) and CODE (CDM V5) = SNOMED (Latest update: 01-Aug-2024), then downloaded the archive (contains both `CONCEPT.csv` and `CONCEPT_RELATIONSHIP.csv`), then applied proper CSV formatting (with `xsv fmt -d"\t"`) to fix bad escaping.

* [[file-omop-concept-relationships]] OMOP (LOINC + SNOMED) – Concept relationships
** name: `CONCEPT_RELATIONSHIP.xsv_fmt.XXH64_31f9def1c5819935.csv`
** source: From https://athena.ohdsi.org/vocabulary/list[OHDSI Athena], then selected CODE (CDM V5) = LOINC (Latest update: 06-Aug-2024) and CODE (CDM V5) = SNOMED (Latest update: 01-Aug-2024), then downloaded the archive (contains both `CONCEPT.csv` and `CONCEPT_RELATIONSHIP.csv`), then applied proper CSV formatting (with `xsv fmt -d"\t"`) to fix bad escaping.

* [[file-kanta-lab-metadata]] Kanta lab – Metadata
** name: `n_people_alive_in_kanta_time.XXH64_fc8010f7a8ad4a08.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-npeople]] Kanta lab – Stats N People by sex
** name: `count_by_sex.XXH64_55ab7400905bd063.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-median-n-measurements]] Kanta lab – Median N measurements
** name: `median_n_measurements.XXH64_11badf7e9f82495c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-people-with-two-plus-records]] Kanta lab – Percent people with 2+ records
** name: `percent_people_two_or_more_records.XXH64_972d77909204a603.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-median-years-first-to-last]] Kanta lab – Median years from first to last record
** name: `median_duration_first_to_last_record.XXH64_39b36dabb238daea.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-stats]] Kanta lab – QC tables stats
** name: `qc_tables.XXH64_4e688fbd2d242617.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-dist-values]] Kanta lab – QC tables distribution values
** name: `qc_tables__distribution_measurement_value__stats.XXH64_effecc3338be8288.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-dist-bins-definitions]] Kanta lab – QC tables distributin binning
** name: `qc_tables__distribution_measurement_value__bins_definitions.XXH64_e53042b0179eab9f.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-test-outcomes]] Kanta lab – QC tables test outcomes
** name: `qc_tables__test_outcome_counts.XXH64_c988a029dbd166a8.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-continuous-stats]] Kanta lab – Distribution lab values / continuous / stats
** name: `measurement_continuous_value_harmonized_distribution__stats.XXH64_ad2abf42d92ae80d.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-continuous-binning]] Kanta lab – Distribution lab values / continuous / binning
** name: `measurement_continuous_value_harmonized_distribution__bins_definitions.XXH64_dc446298aba8b55c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-discrete]] Kanta lab – Distribution lab values / discrete
** name: `measurement_discrete_value_harmonized_distribution__stats.XXH64_87049cbce30f44f8.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-yob-stats]] Kanta lab – Distribution year of birth / stats
** name: `year_of_birth_distribution__stats.XXH64_ec4595969b4faf5c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-yob-binning]] Kanta lab – Distribution year of brith / binning
** name: `year_of_birth_distribution__bins_definitions.XXH64_4aca92fb74464f61.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-first]] Kanta lab – Distribution age at first measurement
** name: `age_first_meas_distribution__stats.XXH64_f566d8fa7f7f211b.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-last]] Kanta lab – Distribution age at last measurement
** name: `age_last_meas_distribution__stats.XXH64_c94a7b62616cf8aa.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-registry]] Kanta lab – Distribution age at registry start
** name: `age_registry_starts_distribution__stats.XXH64_vc8835448eff8ec36.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-binning]] Kanta lab – Distribution age / binning
** name: `age_distributions__bins_definitions.XXH64_263a39b76cfaf733.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-duration-stats]] Kanta lab – Distribution duration from first to last record / stats
** name: `duration_first_to_last_distribution__stats.XXH64_6003a4f0e15f3431.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-duration-binning]] Kanta lab – Distribution duration from first to last record / binning
** name: `duration_first_to_last_distribution__bins_definitions.XXH64_96485130b0e75ae1.json`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-years-stats]] Kanta lab – Distribution N measurements over the years / stats
** name: `n_measurements_over_years_distribution__stats.XXH64_dcc30754d0572a7c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-years-binning]] Kanta lab – Distribution N measurements over the years / binning
** name: `n_measurements_over_years_distribution__bins_definitions.XXH64_71c05267fbc20fca.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-nmeas-person-stats]] Kanta lab – Distribution N measurements by person / stats
** name: `n_measurements_per_person_distribution__stats.XXH64_f09eff1ce99c611a.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-nmeas-person-binning]] Kanta lab – Distribution N measurements by person / binning
** name: `n_records_per_person_distribution__bins_definitions.XXH64_83018a99366a1bfa.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-value-range-stats]] Kanta lab – Distribution value range / stats
** name: `value_range_distributions__stats.XXH64_05ab452633715dbe.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-value-range-binning]] Kanta lab – Distribution value range / binning
** name: `value_range_distributions__bins_definitions.XXH64_7ce4b5f6945e9831.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-reference-range-table]] Kanta lab – Reference range table
** name: `reference_range_tables.XXH64_e06dbb1fd581024e.jsonl`
** source: Risteys Kanta lab pipeline
