Risteys – Web portal
====================

This directory contains the code to power the online FinRegistry-FinnGen Risteys web portal. For the data pipeline, please check the link:../pipeline/README.md[pipeline] directory.

The project is based on the https://phoenixframework.org/[Phoenix web framework].
This framework is written in https://elixir-lang.org/[elixir], which is also used to do data pre-processing and import data into the database.
The front-end interactions are using https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html[Phoenix LiveView].


Setting up a development environment
------------------------------------

Requirements
~~~~~~~~~~~~

- https://elixir-lang.org/install.html[elixir]
- PostgreSQL database


Configuration
~~~~~~~~~~~~~

Some configuration files contain secret credentials, therefore are not present in this public GitHub repository. Risteys developers can get them by requesting access to the GitLab repository `risteys/risteys_secrets`.


Running
~~~~~~~
Make sure you are in the directory `risteys_elixir`, then run the command

[source,bash]
----
mix phx.server
----

You can now access Risteys at http://localhost:4000


Importing data
--------------

Once the Risteys web server is running we still need to put data there.

If you need to compute the statistics by yourself, then check the link:../pipeline/README.md[pipeline documentation].

When you have the data, you can proceed to import it into the Risteys database.
The scripts to import data files into the Risteys database are in this current directory (`risteys_elixir`) and they should be run from that directory, for example:

[source,bash]
----
mix run import_icd9.exs <path-to-input-file>
----


Import scripts should be run in this order:

1. import_icd10.exs, using:
  - <<file-medcode,FG Medcode>>

2. import_icd9.exs, using:
  - <<file-medcode,FG Medcode>>

3. import_endpoint_csv.exs, using:
  - <<file-endp-defs,FG Endpoint definitions>>
  - <<file-endp-main-tag,FG Endpoint main tag>>
  - <<file-endp-taglist,FG Endpoint tag list>>
  - <<file-icd10,ICD-10>>
  - <<file-endp-selected-core,FG Endpoint selected core>>

4. import_intermediate_counts.exs, using:
  - <<file-interm-counts,FG intermediate counts>> and `FG` as dataset argument.

5. import_ontology.exs, using:
  - <<file-ontology,Risteys ontology>>
  - <<file-corrected-descriptions,Risteys corrected endpoint descriptions>>

6. import_excluded_endpoints.exs, using:
  - <<file-excluded_endp,FinRegistry excluded endpoints>>

7. import_key_figures.exs, using:
  - <<file-key-fig-FR-all,Risteys FinRegistry key figures of full population>> and `FR` as dataset argument

8. import_key_figures.exs, using:
  - <<file-key-fig-FR-index,Risteys FinRegistry key figures of index-persons>> and `FR_index` as dataset argument

9. import_key_figures.exs, using:
  - <<file-key-fig-FG,Risteys FinnGen key figures>> and `FG` as dataset argument

10. import_distributions.exs, using:
  - <<file-distrib-age-FR,Risteys FinRegistry age distributions>> and `age` and `FR` as arguments

11. import_distributions.exs, using:
  - <<file-distrib-year-FR,Risteys FinRegistry year distributions>> and `year` and `FR` as arguments

12. import_distributions.exs, using:
  - <<file-distrib-age-FG,Risteys FinnGen age distributions>> and `age` and `FG` as arguments

13. import_distributions.exs, using:
  - <<file-distrib-year-FG,Risteys FinnGen year distributions>> and `year` and `FG` as arguments

14. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FR,Risteys FinRegistry cumulative incidence>> and `FR` as argument

15. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FG,Risteys FinnGen cumulative incidence>> and `FG` as argument

16. import_interactive_mortality_baseline.exs, using:
  - <<file-mortality-baseline,Risteys FinRegistry mortality baseline cumulative hazards>>

17. import_interactive_mortality_params.exs, using:
  - <<file-mortality-params,Risteys FinRegistry mortality parameters>>

18. import_mortality_counts.exs, using:
  - <<file-mortality-counts,Risteys FinRegistry mortality counts>>

19. import_correlations.exs, using:
  - <<file-corr-pheno-geno,FinnGen phenotypic + genotypic correlations>>
  - <<file-coloc-variants,FinnGen coloc variants>>

20. import_case_overlaps_fr.exs, using:
  - <<file-case-overlaps-FR, FinRegistry case overlaps>>

21. import_coxhr.exs, using
  - <<file-surv-FR, FinRegistry survival analysis results>>

22. import_genetic_correlations.exs, using
  - <<file-gen-correlations, FinnGen LDSC genetic correlations>>

23. import_genes.exs, using
  - <<file-havana-genes, HAVANA gene list>>

24. import_upset_plots.exs, using
  - <<file-upset-plots, Upset Plots>> and `FG` as dataset argument

25. import_codewas.exs, using
  - <<file-codewas-endpoints, CodeWAS Endpoints>>
  - <<file-codewas-codelist, CodeWAS code list>>

26. `Risteys.LabWAS.import_stats`, using:
  - <<file-labwas, LabWAS data>>

27. `Risteys.OMOP.import_lab_test_omop_concepts`, using:
  - <<file-kanta-lab-omopid-list, Kanta lab – List of OMOP Concept IDs>>
  - <<file-omop-concepts, OMOP (LOINC + SNOMED) – Concepts>>
  - <<file-omop-concept-relationships, OMOP (LOINC + SNOMED) – Concept relationships>>
+
Can set a longer database timeout if needed, likeso:
+
[source,sh]
----
DATABASE_QUERY_TIMEOUT=120000 iex -S mix
----

28. `Risteys.LabTestStats.import_dataset_metadata`, using:
  - <<file-kanta-lab-metadata, Kanta lab – Metadata>>

29. `Risteys.LabTestStats.import_stats_npeople`, using:
  - <<file-kanta-lab-npeople, Kanta lab – Stats N People by sex>>

30. `Risteys.LabTestStats.import_stats_median_n_measurements`, using:
  - <<file-kanta-lab-median-n-measurements, Kanta lab – Median N measurements>>

31. `Risteys.LabTestStats.import_stats_people_with_two_plus_records`, using:
  - <<file-kanta-lab-people-with-two-plus-records, Kanta lab – Percent people with 2+ records>>

32. `Risteys.LabTestStats.import_stats_median_years_first_to_last`, using:
  - <<file-kanta-lab-median-years-first-to-last, Kanta lab – Median years from first to last record>>

33. `Risteys.LabTestStats.import_qc_tables`, using:
  - <<file-kanta-lab-qc-tables-stats, Kanta lab – QC tables stats>>
  - <<file-kanta-lab-qc-tables-dist-values, Kanta lab – QC tables distribution values>>
  - <<file-kanta-lab-qc-tables-dist-bins-definitions, Kanta lab – QC tables distribution binning>>
  - <<file-kanta-lab-qc-tables-test-outcomes, Kanta lab – QC tables test outcomes>>

34. `Risteys.LabTestStats.import_stats_distribution_lab_values`, using:
  - <<file-kanta-lab-dist-lab-values-continuous-stats, Kanta lab – Distribution lab values / continuous / stats>>
  - <<file-kanta-lab-dist-lab-values-continuous-binning, Kanta lab – Distribution lab values / continuous / binning>>
  - <<file-kanta-lab-dist-lab-values-discrete, Kanta lab – Distribution lab values / discrete>>

35. `Risteys.LabTestStats.import_stats_distribution_year_of_birth`, using:
  - <<file-kanta-lab-dist-yob-stats, Kanta lab – Distribution year of birth / stats>>
  - <<file-kanta-lab-dist-yob-binning, Kanta lab – Distribution year of birth / binning>>

36. `Risteys.LabTestStats.import_stats_distribution_age_first_measurement`, using:
  - <<file-kanta-lab-dist-age-first, Kanta lab – Distribution age at first measurement>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

37. `Risteys.LabTestStats.import_stats_distribution_age_last_measurement`, using:
  - <<file-kanta-lab-dist-age-last, Kanta lab – Distribution age at last measurement>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

38. `Risteys.LabTestStats.import_stats_distribution_age_start_of_registry`, using:
  - <<file-kanta-lab-dist-age-registry, Kanta lab – Distribution age at registry start>>
  - <<file-kanta-lab-dist-age-binning, Kanta lab – Distribution age / binning>>

39. `Risteys.LabTestStats.import_stats_distribution_duration_first_to_last_measurement`, using:
  - <<file-kanta-lab-dist-duration-stats, Kanta lab – Distribution duration from first to last record / stats>>
  - <<file-kanta-lab-dist-duration-binning, Kanta lab – Distribution duration from first to last record / binning>>

40. `Risteys.LabTestStats.import_stats_distribution_n_measurement_over_years`, using:
  - <<file-kanta-lab-dist-years-stats, Kanta lab – Distribution N measurements over the years / stats>>
  - <<file-kanta-lab-dist-years-binning, Kanta lab – Distribution N measurements over the years / binning>>

41. `Risteys.LabTestStats.import_stats_distribution_n_measurements_per_person`, using:
  - <<file-kanta-lab-dist-nmeas-person-stats, Kanta lab – Distribution N measurements by person / stats>>
  - <<file-kanta-lab-dist-nmeas-person-binning, Kanta lab – Distribution N measurements by person / binning>>

42. `Risteys.LabTestStats.import_stats_distribution_value_range_per_person`, using:
  - <<file-kanta-lab-dist-value-range-stats, Kanta lab – Distribution value range / stats>>
  - <<file-kanta-lab-dist-value-range-binning, Kanta lab – Distribution value range / binning>>

43. `Risteys.LabTestStats.import_reference_range_tables`, using:
  - <<file-kanta-lab-reference-range-table, Kanta lab – Reference range table>>


File list
~~~~~~~~~

* [[file-icd10]]ICD-10
** name: `ICD10_koodistopalvelu_2015-08_26_utf8__XXH64_71956a051f960e51.csv`
** source: https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=23&versionKey=58[Kela Kansallinen koodistopalvelu]

* [[file-medcode]]FinnGen medcode
** name: `finngen_R9_medcode_ref__XXH64_708053b379a04020.tsv`
** source: FinnGen - Library Green

* [[file-endp-defs]]FinnGen endpoint definitions
** name: `finngen_R14_endpoint_core_noncore_1.0.added_omit__XXH64_d4d20de773b28150.csv`
** source: Merging of `finngen_R14_endpoint_core_noncore_1.0.xlsx` and `OMIT` column from `Endpoints_Controls_FINNGEN_ENDPOINTS_DF14_Final_2026-02-13.xlsx` - FinnGen clinical team - https://github.com/FINNGEN/Df12-endpoint-and-control-definitions/[GitHub]

* [[file-endp-main-tag]]FinnGen endpoint main tag
** name: `FINNGEN_ENDPOINTS_DF14_Final_2026-02-13.names_tagged_ordered__XXH64_5c05f0c59c7bb09c.txt`
** source: FinnGen clinical team - Sharepoint

* [[file-endp-taglist]]FinnGen endpoint tag list
** name: `TAGLIST_DF14.fixed__XXH64_5f57e7bbf8cc4f04.csv`
** source: FinnGen clinical team - https://github.com/FINNGEN/DF13-endpoint-and-control-definitions/[GitHub]

* [[file-endp-selected-core]]FinnGen endpoint selected core
** name: `finngen_correlation_clusters_DF8__XXH64_0d9f3a10306791f5.csv`
** source: FinnGen clinical team

* [[file-interm-counts]]FinnGen endpoint intermediate counts
** name: `finngen_endpoints_intermediate_counts_green_export_R14_v2__XXH64_60671058c52f96fb.txt`
** source: FinnGen registry team

* [[file-ontology]]Risteys ontology
** name: `finngen_ontology_2022-08-22__XXH64_2a8d4690fa4ae89a.json`
** source: Risteys pipeline

* [[file-corrected-descriptions]]Risteys corrected endpoint description
** name: `corrected-endpoint-descriptions.airtable-export.2026-03-31__XXH64_2d2343a4c58da77d.csv`
** source: Risteys Airtable

* [[file-excluded_endp]]FinRegistry excluded endpoints
** name: `excluded_endpoints_FR_Risteys_R14__XXH64_d3c9406721b2a611.csv`
** source: Risteys script `exclude_endpoints_finregistry.py`

* [[file-key-fig-FR-all]]Risteys FinRegistry key figures, all individuals
** name: `key_figures_all_2022-10-10_with_EXALLC_EXMORE__XXH64_920b310de04e72e7.csv`
** source: Risteys pipeline

* [[file-key-fig-FR-index]]Risteys FinRegistry key figures, only index-persons
** name: `key_figures_index_2022-10-10_with_EXALLC_EXMORE__XXH64_c62d6a466a0512a1.csv`
** source: Risteys pipeline

* [[file-key-fig-FG]]Risteys FinnGen key figures
** name: `key_figures_all_2026-04-01__XXH64_12766c74ec850a26.csv`
** source: Risteys pipeline

* [[file-distrib-age-FR]]Risteys FinRegistry age distributions
** name: `distribution_age_2022-10-10_with_EXALLC_EXMORE__XXH64_edd7be5c03a84317.csv`
** source: Risteys pipeline

* [[file-distrib-year-FR]]Risteys FinRegistry year distributions
** name: `distribution_year_2022-10-10_with_EXALLC_EXMORE__XXH64_a5ea390cd797b6e3.csv`
** source: Risteys pipeline

* [[file-distrib-age-FG]]Risteys FinnGen age distributions
** name: `distribution_age_2026-04-01__XXH64_0d9230a382027bb3.csv`
** source: Risteys pipeline

* [[file-distrib-year-FG]]Risteys FinnGen year distributions
** name: `distribution_year_2026-04-01__XXH64_6328a6fe4f84e3af.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FR]]Risteys FinRegistry cumulative incidence
** name: `cumulative_incidence_2022-10-10_with_EXALLC_EXMORE__XXH64_c08ae173edf55e72.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FG]]Risteys FinnGen cumulative incidence
** name: `all_cumulative_incidence__XXH64_e218602b365df0dc.csv`
** source: Risteys pipeline

* [[file-mortality-baseline]]Risteys FinRegistry mortality baseline cumulative hazards
** name: `mortality_baseline_cumulative_hazard_2022-10-11_with_EXALLC_EXMORE__XXH64_0088608aa7e021bd.csv`
** source: Risteys pipeline

* [[file-mortality-params]]Risteys FinRegistry mortality parameters
** name: `mortality_params_2022-10-11_with_EXALLC_EXMORE__XXH64_8f4fdc15e1c061c1.csv`
** source: Risteys pipeline

* [[file-mortality-counts]]Risteys FinRegistry mortality counts
** name: `mortality_counts_2022-10-11_with_EXALLC_EXMORE__XXH64_f7f9581772ec80c6.csv`
** source: Risteys pipeline

* [[file-corr-pheno-geno]]FinnGen phenotypic + genotypic correlations
** name: `corr_pheno-fg-r14_geno-fg-r14_full-join__2026-04-27__XXH64_083024564ed2ce10.csv.zst`
** source: https://github.com/FINNGEN/endpcorr[FinnGen correlation pipeline] for the phenotypic file, merged with genotypic correlation file from FinnGen analysis team

* [[file-coloc-variants]]FinnGen coloc variants
** name: `r14.autoreport.compare.pval_lt_5e_08.r2_gt_0_8.keep_cs.variants__XXH64_9c2caa79ec700a99.csv`
** source: FinnGen analysis team

* [[file-case-overlaps-FR]] FinRegistry case overlaps
** name: `case_overlap_2022-12-31__XXH64_fb1ca5ba80e4a0ba.csv.zst`
** source: Risteys pipeline

* [[file-surv-FR]] FinRegistry survival analysis results
** name: `surv_priority_endpoints_2022-12-25__XXH64_b92220411f705ef2.csv`
** source: Risteys pipeline

* [[file-gen-correlations]] FinnGen LDSC genetic correlations
** name: `finngen_R14_FIN.ldsc.summary__XXH64_cadd9e219f9892f7.tsv`
** source: FinnGen Green library

* [[file-havana-genes]] HAVANA gene list
** name: `havana__XXH64_085a38684d85191e.json`
** source: HAVANA through FinnGen

* [[file-upset-plots]] Upset Plots
** name: `upset_plots_DF14_2026-03-19__XXH64_890560aaa16181a4.tar.zst`
** source: Harri S, FinnGen Phenotype team

* [[file-codewas-endpoints]] CodeWAS Endpoints
** name: `codewas-from-xwas.description.nested__XXH64_f5f4a55cfd552705.jsonl.zst`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team; then applied the two following SQL queries with DuckDB:
+
[source,sql]
----
copy (
    with source_subset as (
        select *
        from codewas_endpoints_df14_v1
        where
            -- Keep only cohort with >=50 cases and controls
            (n_cases_total >= 50)
            and (n_controls_total >= 50)
            -- Keep only records with nlog10p >= MIN_NLOG10P
            and (counts_mlogp > 6.0)
    )

    select
        ENDPOINT as endpoint_name,
        n_cases_total::UINT64 as n_matched_cases,
        n_controls_total::UINT64 as n_matched_controls,
        FG_CODE1 as code__code1,
        FG_CODE2 as code__code2,
        FG_CODE3 as code__code3,
        vocabulary_id,
        -- Replace Infinity with max double, because Infinity as a double/float
        -- is not JSON compliant and will fail to parse downstream.
        if(
            isinf(counts_odds_ratio),
            1.7976931348623157e+308,
            counts_odds_ratio
        ) as code__odds_ratio,
        counts_mlogp as code__nlog10p,
        -- Greenize the Ns
        if(n_cases_with_code < 5, NULL, n_cases_with_code::UINT64) as code__n_matched_cases,
        if(n_controls_with_code < 5, NULL, n_controls_with_code::UINT64) as code__n_matched_controls
    from source_subset
)
to 'codewas-from-xwas.flat.subset.green.jsonl.zst';
----
+
[source,sql]
----
copy (
    with full_table_flat as (
        select *
        from 'r14/xWas.Javier-Sandbox/codewas-from-xwas.flat.subset.green.jsonl.zst' as counts
        left join 'fg_codes_info_v9.full.csv' as codes
            on  -- Using `is not distinct from` to join on NULL also
                counts.code__code1   is not distinct from codes.FG_CODE1
            and counts.code__code2   is not distinct from codes.FG_CODE2
            and counts.code__code3   is not distinct from codes.FG_CODE3
            and counts.vocabulary_id is not distinct from codes.vocabulary_id
    )
    select
        endpoint_name,
        n_matched_cases,
        n_matched_controls,
        array_agg(
            struct_pack(
                code1              := code__code1,
                code2              := code__code2,
                code3              := code__code3,
                description        := name_en,
                vocabulary         := vocabulary_id,
                -- Replace Infinity with max double, because Infinity as a double/float
                -- is not JSON compliant and will fail to parse downstream.
                odds_ratio         := code__odds_ratio,
                nlog10p            := code__nlog10p,
                -- Greenize the Ns
                n_matched_cases    := code__n_matched_cases,
                n_matched_controls := code__n_matched_controls
            )
        ) as codes
    from full_table_flat
    group by endpoint_name, n_matched_cases, n_matched_controls
)
to 'r14/xWas.Javier-Sandbox/codewas-from-xwas.description.nested.jsonl.zst'
;
----

* [[file-codewas-codelist]] CodeWAS code list
** name: `fg_codes_info_v9.full__XXH64_9fbb9823f3a973a6.csv`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team.

* [[file-labwas]] LabWAS data
** name: `labwas-from-xwas.XXH64_12345b52088d7eb2.jsonl.zst`
** source: Red CodeWAS data from Javier G-T as a DuckDB file, FinnGen Phenotype Team; then applied SQL query with DuckDB:
+
[source,sql]
----
copy (
    WITH omop AS
        (
            SELECT
                concept_id,
                concept_name
            FROM concept
        )
    SELECT
        ENDPOINT AS FG_Endpoint,
        CAST(labwas_endpoints_df14_v1.CONCEPT_ID as VARCHAR) AS OMOP_Concept_ID,
        omop.concept_name AS OMOP_Concept_Name,
        CAST(n_cases_total as UINT64) AS FG_Endpoint_N_Cases,
        CAST(n_controls_total as UINT64) AS FG_Endpoint_N_Controls,
        CAST(n_cases_with_test as UINT64) AS With_Measurement_N_Cases,
        CAST(n_controls_with_test as UINT64) AS With_Measurement_N_Controls,
        if(isinf(counts_odds_ratio), 1.7976931348623157e+308, counts_odds_ratio) AS With_Measurement_Odds_Ratio,
        if(isinf(counts_mlogp), 1.7976931348623157e+308, counts_mlogp) AS With_Measurement_mlogp,
        mean_n_measurements_cases AS Mean_N_Measurements_Cases,
        mean_n_measurements_controls AS Mean_N_Measurements_Controls,
        CAST(n_cases_with_test_and_value as UINT64) AS Mean_Value_N_Cases,
        CAST(n_controls_with_test_and_value as UINT64) AS Mean_Value_N_Controls,
        unit_value_cases As Mean_Value_Unit,
        mean_value_cases AS Mean_Value_Cases,
        mean_value_controls AS Mean_Value_Controls,
        if(isinf(values_mlogp), 1.7976931348623157e+308, values_mlogp) AS Mean_Value_mlogp
    FROM labwas_endpoints_df14_v1
    LEFT JOIN omop ON labwas_endpoints_df14_v1.CONCEPT_ID = omop.concept_id
    WHERE (
        ((FG_Endpoint_N_Cases = 0) OR (FG_Endpoint_N_Cases >= 5))
        AND ((FG_Endpoint_N_Controls = 0) OR (FG_Endpoint_N_Controls >= 5))
        AND ((With_Measurement_N_Cases = 0) OR (With_Measurement_N_Cases >= 5))
        AND ((With_Measurement_N_Controls = 0) OR (With_Measurement_N_Controls >= 5))
        AND ((Mean_Value_N_Cases = 0) OR (Mean_Value_N_Cases >= 5))
        AND ((Mean_Value_N_Controls = 0) OR (Mean_Value_N_Controls >= 5))
        AND (((FG_Endpoint_N_Cases - With_Measurement_N_Cases) = 0) OR ((FG_Endpoint_N_Cases - With_Measurement_N_Cases) >= 5))
        AND (((FG_Endpoint_N_Controls - With_Measurement_N_Controls) = 0) OR ((FG_Endpoint_N_Controls - With_Measurement_N_Controls) >= 5))
        AND (((With_Measurement_N_Cases - Mean_Value_N_Cases) = 0) OR ((With_Measurement_N_Cases - Mean_Value_N_Cases) >= 5))
        AND (((With_Measurement_N_Controls - Mean_Value_N_Controls) = 0) OR ((With_Measurement_N_Controls - Mean_Value_N_Controls) >= 5))
    )
)
to 'labwas-from-xwas.jsonl.zst' (format JSON, array FALSE, compression 'zstd');
----

* [[file-kanta-lab-omopid-list]] Kanta lab – List of OMOP Concept IDs
** name: `all_omop_ids__XXH64_4657da325077a314.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-omop-concepts]] OMOP (LOINC + SNOMED) – Concepts
** name: `CONCEPT.xsv_fmt.XXH64_3db4f0c961550c25.csv`
** source: From https://athena.ohdsi.org/vocabulary/list[OHDSI Athena], then selected CODE (CDM V5) = LOINC (Latest update: 06-Aug-2024) and CODE (CDM V5) = SNOMED (Latest update: 01-Aug-2024), then downloaded the archive (contains both `CONCEPT.csv` and `CONCEPT_RELATIONSHIP.csv`), then applied proper CSV formatting (with `xsv fmt -d"\t"`) to fix bad escaping.

* [[file-omop-concept-relationships]] OMOP (LOINC + SNOMED) – Concept relationships
** name: `CONCEPT_RELATIONSHIP.xsv_fmt.XXH64_31f9def1c5819935.csv`
** source: From https://athena.ohdsi.org/vocabulary/list[OHDSI Athena], then selected CODE (CDM V5) = LOINC (Latest update: 06-Aug-2024) and CODE (CDM V5) = SNOMED (Latest update: 01-Aug-2024), then downloaded the archive (contains both `CONCEPT.csv` and `CONCEPT_RELATIONSHIP.csv`), then applied proper CSV formatting (with `xsv fmt -d"\t"`) to fix bad escaping.

* [[file-kanta-lab-metadata]] Kanta lab – Metadata
** name: `n_people_alive_in_kanta_time__XXH64_cbc2155faf1a2c5c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-npeople]] Kanta lab – Stats N People by sex
** name: `count_by_sex.XXH64_2a9ae66ad6e18b6c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-median-n-measurements]] Kanta lab – Median N measurements
** name: `median_n_measurements.XXH64_11badf7e9f82495c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-people-with-two-plus-records]] Kanta lab – Percent people with 2+ records
** name: `percent_people_two_or_more_records.XXH64_972d77909204a603.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-median-years-first-to-last]] Kanta lab – Median years from first to last record
** name: `median_duration_first_to_last_record.XXH64_ecd576f1e820bcec.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-stats]] Kanta lab – QC tables stats
** name: `qc_tables.XXH64_ca37f7eec0f8c611.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-dist-values]] Kanta lab – QC tables distribution values
** name: `qc_tables__distribution_measurement_value__stats.XXH64_e1334713db9eff15.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-dist-bins-definitions]] Kanta lab – QC tables distribution binning
** name: `qc_tables__distribution_measurement_value__bins_definitions.XXH64_03f53a1e3c3c7344.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-qc-tables-test-outcomes]] Kanta lab – QC tables test outcomes
** name: `qc_tables__test_outcome_counts.XXH64_72af626e4b9741e3.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-continuous-stats]] Kanta lab – Distribution lab values / continuous / stats
** name: `measurement_continuous_value_harmonized_distribution__stats.XXH64_aff2df95b7f9ce69.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-continuous-binning]] Kanta lab – Distribution lab values / continuous / binning
** name: `measurement_continuous_value_harmonized_distribution__bins_definitions.XXH64_ada08248ae44f1cf.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-lab-values-discrete]] Kanta lab – Distribution lab values / discrete
** name: `measurement_discrete_value_harmonized_distribution__stats.XXH64_aa532e7a7f058e8d.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-yob-stats]] Kanta lab – Distribution year of birth / stats
** name: `year_of_birth_distribution__stats.XXH64_48455fad2b1107b3.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-yob-binning]] Kanta lab – Distribution year of birth / binning
** name: `year_of_birth_distribution__bins_definitions.XXH64_cb9fbff619981ebf.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-first]] Kanta lab – Distribution age at first measurement
** name: `age_first_meas_distribution__stats.XXH64_271c26c847e4583f.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-last]] Kanta lab – Distribution age at last measurement
** name: `age_last_meas_distribution__stats.XXH64_c5cfc5f8c048e7e6.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-registry]] Kanta lab – Distribution age at registry start
** name: `age_registry_starts_distribution__stats.XXH64_fb69f161c6d96c45.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-age-binning]] Kanta lab – Distribution age / binning
** name: `age_distributions__bins_definitions.XXH64_3b40b910a515b0fa.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-duration-stats]] Kanta lab – Distribution duration from first to last record / stats
** name: `duration_first_to_last_distribution__stats.XXH64_7a6fa726ca830a8b.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-duration-binning]] Kanta lab – Distribution duration from first to last record / binning
** name: `duration_first_to_last_distribution__bins_definitions.XXH64_3fb887b7c0102604.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-years-stats]] Kanta lab – Distribution N measurements over the years / stats
** name: `n_measurements_over_years_distribution__stats.XXH64_6899b345987720a5.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-years-binning]] Kanta lab – Distribution N measurements over the years / binning
** name: `n_measurements_over_years_distribution__bins_definitions.XXH64_144b429ebd6bac3a.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-nmeas-person-stats]] Kanta lab – Distribution N measurements by person / stats
** name: `n_measurements_per_person_distribution__stats.XXH64_5e2b2f32250d2b77.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-nmeas-person-binning]] Kanta lab – Distribution N measurements by person / binning
** name: `n_records_per_person_distribution__bins_definitions.XXH64_83018a99366a1bfa.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-value-range-stats]] Kanta lab – Distribution value range / stats
** name: `value_range_distributions__stats.XXH64_2d257a0d7f375f4a.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-dist-value-range-binning]] Kanta lab – Distribution value range / binning
** name: `value_range_distributions__bins_definitions.XXH64_9dd33638743fbb6c.jsonl`
** source: Risteys Kanta lab pipeline

* [[file-kanta-lab-reference-range-table]] Kanta lab – Reference range table
** name: `reference_range_tables.XXH64_242727d5a27baf5d.jsonl`
** source: Risteys Kanta lab pipeline
